trigger:
- master
#strategy:
#  matrix:
#   linux:
#     operatingSystem: ubuntu-latest
#   mac:
#     operatingSystem: macos-latest
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
        steps:
          - script: echo deployment job started for dev
- stage: QA
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
        steps:
          - script: echo deployment job started for QA
         




# steps:
# - script: echo Environments running!
#   displayName: 'Run a one-line script'